### ISSUE TITLE
[BUG] Log step breaks visualization

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-backend#168]
**Describe the bug**
Log selected from drag and drop as a `MIDDLE` step results in YAML where the `log` is actually an `END`, breaking the visualization.

<img width="1397" alt="Screen Shot 2022-09-26 at 7 17 17 pm" src="https://user-images.githubusercontent.com/3844502/192481149-2887a086-b228-4086-bcd7-84c789517b3d.png">

**To Reproduce**
1. Build an integration with postgresql-source -> kafka-sink
2. Add a log step from the mini catalog
3. It generates a YAML. Copy the YAML.
4. Refresh the page
5. Re-add the YAML. The second edge is missing.

And I think the problem is because the log that gets generated for the YAML is an `END` step for some reason. But maybe when you choose it from the mini catalog it's considered a log of type `MIDDLE`?

**Expected behavior**

**Logs**
It produces this YAML:

```
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: integration
spec:
  source:
    ref:
      apiVersion: camel.apache.org/v1alpha1
      name: chuck-norris-source
      kind: Kamelet
  steps:
  - ref:
      apiVersion: camel.apache.org/v1alpha1
      name: chunk-template-action
      kind: Kamelet
  - uri: log:null
  sink:
    ref:
      apiVersion: camel.apache.org/v1alpha1
      name: kafka-sink
      kind: Kamelet
```
