### ISSUE TITLE
[BUG] Problem with parsing integer values in integration endpoint

### ISSUE THREAD

**Issue by mmelko** [KaotoIO/kaoto-backend#283]
**Describe the bug**
Following exception is thrown when  KameletBinding with some integer values  is pasted to the editor:

`Error processing deployment: class java.lang.String cannot be cast to class java.lang.Integer (java.lang.String and java.lang.Integer are in module java.base of loader 'bootstrap') (through reference chain: io.kaoto.backend.api.resource.v1.model.Integration["steps"]->java.util.ImmutableCollections$ListN[0]->io.kaoto.backend.model.step.Step["parameters"]->java.util.LinkedList[0]->io.kaoto.backend.model.parameter.IntegerParameter["value"]`

KameletBinding example:
```
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: integration
spec:
  source:
    ref:
      apiVersion: camel.apache.org/v1alpha1
      name: timer-source
      kind: Kamelet
    properties:
      period:10000
  sink:
    ref:
      apiVersion: camel.apache.org/v1alpha1
      name: log-sink
      kind: Kamelet
```
