### ISSUE TITLE
[BUG] Camel component type is `END` even if it's in between steps

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-backend#352]
**Describe the bug**
When adding a Camel component in a YAML file, and it's a middle step, the `type` returned by the backend is `END` instead of `MIDDLE`. This causes the UI to break, because the UI is checking for the step `type` to determine whether it should keep creating edges (`MIDDLE`) or stop (`END`).

**To Reproduce**
1. Go to Settings
2. Change DSL to Kamelet & save
3. Open Code Editor
4. Paste YAML below
5. See Camel component is not connected

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  annotations:
    camel.apache.org/kamelet.support.level: Preview
    camel.apache.org/catalog.version: main-SNAPSHOT
    camel.apache.org/kamelet.icon: whatever
    camel.apache.org/provider: Apache Software Foundation
    camel.apache.org/kamelet.group: Kaoto
  labels:
    camel.apache.org/kamelet.type: sink
  name: eip-action-sink
spec:
  definition:
    title: EIP Kamelet
    description: Used to test all EIP we implement
    properties: {}
  dependencies:
    - camel:core
    - camel:kamelet
    - camel:bean
    - camel:aws2-eventbridge
    - camel:chunk
  template:
    from:
      uri: kamelet:source
      steps:
        - choice:
            when:
              - simple: "{{?baz}}"
                steps:
                  - load-balance:
                      weighted:
                        distribution-ratio: 2,1
                        round-robin: false
                      steps:
                        - log:
                            message: test
                            logging-level: INFO
                            log-name: yaml
            otherwise:
              steps:
                - remove-header:
                    name: removeme
        - filter:
            simple: "{{?foo}}"
            steps:
              - set-body:
                  simple: abc
              - idempotent-consumer:
                  idempotent-repository: myRepo
                  simple: ${header.id}
                  steps:
                    - set-body:
                        simple: cheesecubez
        - to:
            uri: aws2-eventbridge
        - to:
            uri: chunk:null
```

Alternatively, to see the backend response in JSON:
1. Same steps as above, then:
2. Open the browser console (Chrome)
3. Go to the Network tab, make sure Fetch/XHR requests are selected
4. Scroll down to the very last `integrations` call made
5. Click on the Response tab
6. See the JSON returned from the API (you may need to copy and paste into an IDE for better JSON formatting)

Here is an [example gist](https://gist.github.com/kahboom/6c25a2a2517dc2042f4a00f2df85b805) with the YAML example from above (see the last two steps, `aws2-eventbridge-producer` and `chunk-producer`).

**Expected behavior**
The backend should either not allow the two `END` steps at all, or should be returning them as `MIDDLE` if they are actually meant to be middle steps. But there should not be any steps in the middle with type `END`.

**Environment (please complete the following information):**
 - OS: macOS
 - Output of the `mvn -version` command:
```
Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)
Maven home: /opt/homebrew/Cellar/maven/3.8.5/libexec
Java version: 18.0.1, vendor: Homebrew, runtime: /opt/homebrew/Cellar/openjdk/18.0.1/libexec/openjdk.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "12.6", arch: "aarch64", family: "mac"
```
 - Kaoto Version: 0.5.0-snapshot

**Additional context**
This is what the visualization looks like with the above YAML (can provide more examples if needed, I think `evil-eip` YAML also works for this):

![Screen Shot 2022-11-29 at 4 28 05 pm](https://user-images.githubusercontent.com/3844502/204595390-b1248f42-c16c-4d0c-a8b1-e06d8b63f9e8.png)

### `kamelet-evip-eip`

![kamelet-evil-eip](https://user-images.githubusercontent.com/3844502/204595570-379fb08b-4a9a-4edc-a9f1-f216ab8b697b.png)

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  annotations:
    camel.apache.org/kamelet.icon: cherry
  labels:
    camel.apache.org/kamelet.type: action
  name: eip-action
spec:
  definition:
    title: EIP Kamelet
    description: Used to test all EIP we implement
    properties: {}
  dependencies:
    - camel:core
    - camel:kamelet
  template:
    from:
      uri: kamelet:source
      steps:
        - loop:
            constant: "3"
            copy: true
            steps:
              - delay:
                  expression:
                    simple: ${body}
                  async-delayed: true
        - choice:
            when:
              - simple: "{{?foo}}"
                steps:
                  - dynamic-router:
                      expression:
                        simple: ${body}
                  - set-header:
                      name: bar
                      simple: foo
              - simple: "{{?bar}}"
                steps:
                  - set-property:
                      name: property
                      simple: bar
                  - remove-property:
                      name: property
                  - marshal:
                      json:
                        library: Gson
              - simple: "{{?baz}}"
                steps:
                  - transform:
                      simple: baz
                  - aggregate:
                      correlation-expression:
                        simple: ${header.StockSymbol}
                      aggregation-strategy: myAggregatorStrategy
                      completion-size: 2
                  - log:
                      message: test
                      logging-level: INFO
                      log-name: yaml
            otherwise:
              steps:
                - set-body:
                    simple: ola ke ase
                - remove-header:
                    name: removeme
                - claim-check:
                    operation: Push
                    key: foo
                    filter: header:(foo|bar)
        - filter:
            simple: "{{?foo}}"
            steps:
              - set-body:
                  simple: abc
              - unmarshal:
                  json:
                    unmarshal-type-name: MyClass
              - circuit-breaker:
                  description:
                    text: Another one
                    lang: eng
                  steps:
                    - enrich:
                        expression:
                          simple: ${body}
                    - to:
                        uri: dropbox:put
                        parameters:
                          accessToken: "{{accessToken}}"
                    - convert-body-to:
                        type: java.lang.String
                        charset: UTF8
                  on-fallback:
                    steps:
                      - log:
                          message: test
                          logging-level: INFO
                          log-name: yaml
        - to:
            uri: kamelet:sink
```
