### ISSUE TITLE
[BUG] EIP step disappears in YAML

### ISSUE THREAD

**Issue by kahboom** [KaotoIO/kaoto-backend#400]
**Describe the bug**
If the `POST` request to `/v1/integrations?dsl=KameletBinding` (YAML->JSON) contains an EIP step, it gets removed in the JSON that gets returned. This doesn't happen in the reverse request (JSON->YAML).

**To Reproduce**
1. Go to Source Code editor
2. Click on the edit mode button
3. Paste the following YAML
4. See the EIP step disappears

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: integration
spec:
  source:
    ref:
      apiVersion: camel.apache.org/v1alpha1
      name: aws-kinesis-source
      kind: Kamelet
  sink:
    ref:
      apiVersion: camel.apache.org/v1alpha1
      name: aggregate
      kind: Kamelet
```

This is the same exact YAML that gets returned when you provide JSON instead.

**NOTE:** In the case of the Kaoto VSCode plugin it happens regardless of whether you add it from the canvas or source code editor, which you can test [with these instructions](https://github.com/KaotoIO/vscode-kaoto/blob/main/CONTRIBUTING.md#how-to-manually-test-latest-kaoto-ui). This means that there is currently no way to add an EIP step from the VSCode plugin.

**Expected behavior**
The EIP step should not be removed.

**Logs**
N/A

**Environment (please complete the following information):**
 - OS:  macoS
 - Kaoto Version: Tag v0.5.0

**Additional context**
