### ISSUE TITLE
[BUG] YAML>JSON integration REST returns duplicated START step

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto-backend#497]
**Describe the bug**
 YAML>JSON integration REST returns duplicated START step.

**To Reproduce**
1. POST following YAML to `/v1/integrations`
```yaml
- from:
    uri: activemq:null:queue
    steps:
    - to:
        uri: activemq:null:queue
```
2. See the response JSON has 2 `activemq` steps and both of them have `START` as a type

**Expected behavior**
The 2nd activemq step should be MIDDLE or END

cf. https://github.com/KaotoIO/kaoto-ui/issues/1288
