### ISSUE TITLE
Support multiple routes

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-backend#502]
**Is your feature request related to a problem? Please describe.**

main-yaml example is using top level element route. it has the advantage to allow providing an id to the route.

https://github.com/apache/camel-examples/blob/main/examples/main-yaml/src/main/resources/routes/my-route.yaml

```
- route:
    id: "foo"
    from:
      uri: "quartz:foo?cron={{myCron}}"
      steps:
        - to: "bean:myBean?method=hello"
        - log: "${body}"
        - to: "bean:myBean?method=bye"
        - log: "${body}"
 ```

**Describe the solution you'd like**
 support this other way of defining route

**Describe alternatives you've considered**

**Additional context**

this might be covered when supporting multiple routes? To be verified

**Comment by lhein** [comment]
Other examples I have seen:
```
routes:
  - from:
      uri: file:inputDir
    choice:
      when:
        xpath: "/order[@type='book']"
        to: file:bookOrderDir
      when:
        xpath: "/order[@type='music']"
        to: file:musicOrderDir
      otherwise:
        to: file:unknownOrderDir
```

**Comment by lhein** [comment]
```
camelContext:
  routeBuilders:
    - routeBuilder:
        from:
          uri: file:inputDir
        choice:
          when:
            xpath: "/order[@type='book']"
            to: file:bookOrderDir
          when:
            xpath: "/order[@type='music']"
            to: file:musicOrderDir
          otherwise:
            to: file:unknownOrderDir
```

**Comment by lhein** [comment]
```
camelContext:
  routes:
    - route:
        from:
          uri: file:inputDir1
        to:
          uri: file:outputDir1
    - route:
        from:
          uri: file:inputDir2
        to:
          uri: file:outputDir2
    - route:
        from:
          uri: file:inputDir3
        choice:
          when:
            xpath: "/order[@type='book']"
            to: file:bookOrderDir
          when:
            xpath: "/order[@type='music']"
            to: file:musicOrderDir
          otherwise:
            to: file:unknownOrderDir
```

**Comment by kahboom** [comment]
Related https://github.com/KaotoIO/kaoto-ui/issues/801

**Comment by lhein** [comment]
still work in progress

**Comment by lordrip** [comment]
Related pull request: https://github.com/KaotoIO/kaoto-backend/pull/638

**Comment by Delawen** [comment]
@lordrip that pull request is merged. Is this issue closed?

**Comment by lordrip** [comment]
Hi @delawen not yet, because we still need to support and we're not there yet

```
- route:
    id: "foo"
    from:
      uri: "quartz:foo?cron={{myCron}}"
      steps:
        - to: "bean:myBean?method=hello"
        - log: "${body}"
        - to: "bean:myBean?method=bye"
        - log: "${body}"
```
