### ISSUE TITLE
[BUG] message provided directly for log EIP is removed

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-backend#525]
**Describe the bug**

message provided directly for log EIP is removed

**To Reproduce**
1. Open Source Code edtior
2. Provide:
```yaml
# camel-k: language=yaml

# Write your routes here, for example:
- from:
    uri: "timer:yaml"
    parameters:
      period: "1000"
    steps:
      - setBody:
          constant: "Hello Camel from yaml"
      - log: "${body}"
 ```
3. Click on Sync code
4. The log EIP is removed

```yaml
- from:
    uri: timer:yaml
    parameters:
      period: '1000'
    steps:
    - set-body:
        constant: Hello Camel from yaml
```

**Expected behavior**

Keep the log step with its message

**Logs**

**Environment (please complete the following information):**

OperateFirst

**Additional context**

The sample code is the one generated by Camel Jbang init (like when running `jbang run -Dcamel.jbang.version=3.20.2 camel@apache/camel init demo.yaml`)

**Comment by lordrip** [comment]
@Delawen , the `log` example looks different to what Kaoto generates using the two available `log` step

```yaml
- from:
    uri: timer:yaml
    parameters:
      period: '1000'
    steps:
    - set-body:
        constant: Hello Camel from yaml
    - log: {} # First log
    - to: # second log
        uri: log:null
```

was the provided `log` invalid and that's why got deleted?
