### ISSUE TITLE
[BUG] ids of steps are removed

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-backend#526]
**Describe the bug**

ids provided on steps are removed

**To Reproduce**

1. Go to Source Code editor
2. Provide for instance:
```
- from:
      uri: file:data?noop=true
      id: from-74c5
      steps:
        - log:
            message: ${body}
            id: log-5f36
 ```

4. Click on Sync code
--> the ids are removed, it results to:
```
- from:
    uri: file:data
    parameters:
      noop: 'true'
    steps:
    - log:
        message: ${body}
 ```

**Expected behavior**

**Logs**
If applicable, add logs to help explain your problem.

**Environment (please complete the following information):**
OperateFirst

**Additional context**
real world example using ids: https://github.com/dscope-io/ISO20022/blob/393f7b0221e6a266589611687a5a70d13db43fbd/samples/SwiftCamel/swiftic.camel.yaml
