### ISSUE TITLE
Component not part of default catalog are removed

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-backend#527]
### Describe the Bug

when using a custom component, the step is removed from the code when syncing code.

### Steps to Reproduce the Bug or Issue

1. Open Source code editor
2. Add fo rinstance:
```
- from:
    uri: timer:null
    steps:
    - to:
        uri: myComponent
 ```
 3. Sync code
 --> the not provided by default component is removed

### Platform

OperateFirst
