### ISSUE TITLE
[BUG] Expression is lost in YAML > JSON

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto-backend#548]
**Describe the bug**
Expression breaks in some EIP with some dialect. All EIPs uses expression should behave consistently.

**To Reproduce**
1. Paste this in source code editor
```yaml
- from:
    uri: timer:null
    steps:
    - transform:
        expression:
          jq:
            expression: test
```
2. Click `Sync your code` button
4. See the JSON response

**Expected behavior**
Returned JSON should contain the expression

**Logs**
If applicable, add logs to help explain your problem.

**Environment (please complete the following information):**
 - OS: [e.g. "Linux 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux"]
 - Output of the mvn -version` command
 - Kaoto Version [e.g. 1.0]

**Additional context**
