### ISSUE TITLE
[BUG] Code with expression object is lost in JSON > YAML

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto-backend#554]
**Describe the bug**
The source code is lost with `expression` object

**To Reproduce**
1. Open source code editor
2. Paste following YAML
```yaml
- from:
    uri: timer:null
    steps:
    - set-body:
        expression:
          simple:
            expression: test
```
4. Click `sync your code`
5. See error

**Expected behavior**
Source code shows and the canvas updates

**Logs**

https://user-images.githubusercontent.com/265462/226401582-ae91393e-fb8b-44a3-aa0f-f0b2aad762a6.mp4

**Environment (please complete the following information):**
 - OS: [e.g. "Linux 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux"]
 - Output of the mvn -version` command
 - Kaoto Version [e.g. 1.0]

**Additional context**
