### ISSUE TITLE
[BUG] `expression` object is filled with default values

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto-backend#569]
**Describe the bug**
A variation of https://github.com/KaotoIO/kaoto-backend/issues/503

`expression` object is filled with default values after code sync

**To Reproduce**
1. Open source code editor
2. Paste this code
```yaml
- from:
    uri: timer:null
    steps:
      - choice:
          when:
            - expression:
                simple:
                  expression: choice
```
4. Click `sync your code`
5. YAML is updated with default values
```yaml
- from:
    uri: timer:null
    steps:
    - choice:
        when:
        - expression:
            simple:
              expression: choice
              trim: false
              result-type: 'null'
              id: 'null'
          steps: []
```

**Expected behavior**
Default values are wiped out

**Logs**
If applicable, add logs to help explain your problem.

**Environment (please complete the following information):**
 - OS: [e.g. "Linux 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux"]
 - Output of the mvn -version` command
 - Kaoto Version [e.g. 1.0]

**Additional context**
