### ISSUE TITLE
[BUG] Some placeholders in path parameters are replaced by null

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-backend#577]
**Describe the bug**

Some placeholders in path parameters are replaced by null

**To Reproduce**
1. Open Source code editor
2. Paste
```yaml
- from:
      uri: file:{{customer.file.directory}}
      steps:
        - to:
            uri: sftp://{{sftphost}}:22/files/process
```
4. Click on `sync code`
5. some placeholders are replaced with null:
```yaml
- from:
      uri: file:{{customer.file.directory}}
      steps:
        - to:
            uri: sftp://{{sftphost}}:22/files/process
```
**Expected behavior**

**Logs**
If applicable, add logs to help explain your problem.

**Environment (please complete the following information):**
OperateFirst

**Additional context**
example extract and simplified from https://github.com/pprosser-redhat/SharedServices/blob/3f4019abdf14fcf5b4f44073cdc80fa7c209fc7d/sftpexamplesender/src/main/resources/routes/SendtoSFTP.camel.yaml#L3
