### ISSUE TITLE
[BUG] `SyntaxError: Expected ',' or '}' after property value` when string field has a integer-like source

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-backend#583]
**Describe the bug**

**To Reproduce**
1. Go to source code editor
2. Paste
```
- from:
    uri: slack:test
    parameters:
      maxResults: 1
    steps: []
```
3. Click `Sync code`
4. --> nothing happens in Canvas
5. 

**Expected behavior**

**Logs**
in console log:

```
SyntaxError: Expected ',' or '}' after property value in JSON at position 8351
overrideMethod @ VM510 react_devtools_backend.js:2655
```

The request which seems to be incorrect is:

```
http://kaoto-kaoto.apps.smaug.na.operate-first.cloud/api/v1/integrations
```

with payload:
```
- from:
    uri: slack:test
    parameters:
      maxResults: 1
    steps: []
```

returns response like:
```
{
	"steps": [
		{
			"name": "slack",
			"type": "START",
			"id": "slack-consumer",
			"kind": "Camel-Connector",
			"icon": "data:image/svg+xml;base64,XXXXXXX\n",
			"title": "Slack",
			"description": "Send and receive messages Error processing deployment: java.lang.Integer cannot be cast to java.lang.String (through reference chain: io.kaoto.backend.api.resource.v1.model.Integration["steps"]->java.util.ImmutableCollections$ListN[0]->io.kaoto.backend.model.step.Step["parameters"]->java.util.LinkedList[8]->io.kaoto.backend.model.parameter.StringParameter["value"])
```

it is coming from example from Red Hatter Hugo Guerrero https://github.com/hguerrero/serverless-examples/blob/4233bbc1168eecdc70f2f967ba80adc67b4b070a/knative-slack-demo/camel-source/camel-slack-source.yaml#L24

**Comment by Delawen** [comment]
`maxResults` is a string: https://camel.apache.org/components/3.20.x/slack-component.html#_endpoint_query_option_maxResults

If we use 

```
- from:
    uri: slack:test
    parameters:
      maxResults: '1'
    steps: []
```

(note the quotes) it works.

Anyway, it shouldn't explode.
