### ISSUE TITLE
[BUG] Missing parameters for kamelet defined in URI

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-backend#585]
**Describe the bug**

Missing parameters for kamelet defined in URI.

in combination of removal of unknown properties, it means that it is removing parameters specific to the kamelet when using `sync code`

**To Reproduce**
1. Open Source code editor
2. Paste
```yaml
- from:
      uri: kamelet:timer-source
      id: from-d428
      parameters:
        period: 2
        message: hello
      steps: []
```
3. Click on 'Sync code'
4. --> parameters are removed:
```yaml
- from:
    id: from-d428
    uri: kamelet:timer-source:null
    steps: []
```

or

1. Add a step kamelet
2. Provide template id `timer-source`

**Expected behavior**

maybe as iteration 0, to remove the kamelet from the catalog and mention that it is not supported.
as first iteration to not lose the data
as second iteration to allow to edit the parameter values in the UI

**Logs**
If applicable, add logs to help explain your problem.

**Environment (please complete the following information):**
OperateFirst

**Additional context**

used for instance in Quarkus super heroes example: https://github.com/pprosser-redhat/quarkus-super-heroes/blob/6528f5ee69a1bfaec16b79747f62c574e6f8360a/camelkfordebezium/camelformessaging/messaging.camel.yaml#L5
