### ISSUE TITLE
[BUG] part of marshal step in source is removed when `data-format` attribute is specified

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto-backend#595]
**Describe the bug**
From what I can see from [this document](https://camel.netlify.app/camel-k/latest/languages/yaml.html) the following YAML should be valid
```yaml
- from:
    uri: timer:null
    steps:
    - marshal:
        data-format:
            json:
                library: Gson
```
but is wiped out.

it ends up with:
```yaml
- from:
    uri: timer:null
    steps:
    - marshal:
        data-format:
          json: ''
```

**To Reproduce**
1. Open source code editor and paste above code
2. Click `sync your code`

**Expected behavior**
marshal step is preserved

**Logs**
If applicable, add logs to help explain your problem.

**Environment (please complete the following information):**
 - OS: [e.g. "Linux 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux"]
 - Output of the mvn -version` command
 - Kaoto Version [e.g. 1.0]

**Additional context**
