### ISSUE TITLE
 Log component replaced with Log EIP

### ISSUE THREAD

**Issue by unsortedhashsets** [KaotoIO/kaoto-backend#600]
### Describe the Bug

Log component is replaced with Log EIP with a few conditions:
- the previous step is empty
- Sync up code clicked

Fixture:
```
apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  labels:
    camel.apache.org/kamelet.type: action
  name: integration-action
spec:
  definition:
    title: "null"
    description: "null"
    properties: {}
  dependencies:
    - camel:core
    - camel:timer
    - camel:log
  template:
    from:
      uri: timer:null
      steps:
        - to:
            uri: log:null
```

### Steps to Reproduce the Bug or Issue

1. Use fixture `cypress/e2e/fixtures/TimerLogCamelRoute.yaml` or from the comment upper
![Screenshot from 2023-03-30 11-14-31](https://user-images.githubusercontent.com/46084942/228789195-07dc38a5-ac1a-4c11-b036-f029c77b0674.png)

2. Delete first step
![Screenshot from 2023-03-30 11-14-46](https://user-images.githubusercontent.com/46084942/228789237-2fda9b5b-f019-4460-a91a-081f9b7fec9c.png)

3. Sync up code
![Screenshot from 2023-03-30 11-14-16](https://user-images.githubusercontent.com/46084942/228789252-660e491c-acfc-450b-9b87-8176e78ed08b.png)

### Platform

 - OS: [RHEL-8.6]
 - Browser: [Chrome]
 - Version: [110]

**Comment by igarashitm** [comment]
It's already broken on step2, log shouldn't be moved as `from`
```yaml
- from:
    uri: 'log:'
    steps: []
```
