### ISSUE TITLE
[BUG] Support data-format dialect

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto-backend#611]
**Describe the bug**
https://github.com/KaotoIO/kaoto-backend/pull/602 will fix for this implicit dataformat dialect
```yaml
- from:
    uri: timer:null
    steps:
    - marshal:
            json:
                library: Gson
```

But this explicit dialect is still unsupported
```yaml
- from:
    uri: timer:null
    steps:
    - marshal:
        data-format:
            json:
                library: Gson
```

**To Reproduce**
1. Paste above explicit dialect YAML
2. click `sync your code` 

**Expected behavior**

**Logs**
If applicable, add logs to help explain your problem.

**Environment (please complete the following information):**
 - OS: [e.g. "Linux 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux"]
 - Output of the mvn -version` command
 - Kaoto Version [e.g. 1.0]

**Additional context**
