### ISSUE TITLE
[BUG] Native build backend wipes out the expression content in verbose dialect

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto-backend#617]
**Describe the bug**
While it's preserved with `quarkus:dev`, with native build, the expression content is wiped out with the `/expression/simple/expression` version of a dialect.

**To Reproduce**
1. Paste this YAML
```yaml
- from:
    uri: "timer:trigger-gitter-streaming"
    parameters:
        repeatCount: 1
    steps:
        - log:
              message: Opening connection to Gitter...
        - setHeader:
              name: Authorization
              expression:
                  simple:
                      expression: "Bearer {{token}}"
        - to:
              uri: >-
                  [https://gitter.ems.host/_matrix/client/v3/sync?filter={](https://gitter.ems.host/_matrix/client/v3/sync?filter=%7B)"account_data":{"not_types":["*"]},"room":{"account_data":{"not_types":["*"]},"rooms":["{{room}}"],"timeline":{"limit":1,"types":["m.room.message"]},"state":{"not_types":["*"]}
                  } }
        - log:
              message: Gitter HTTP Streaming started
```
2. Click on 'Sync your code'
3. With native build the expression is wiped out, while it's preserved with `quarkus:dev`
#### quarkus:dev
https://user-images.githubusercontent.com/265462/230142934-7db3d33e-c512-473a-839b-92d478478330.mp4

#### native
https://user-images.githubusercontent.com/265462/230142998-8cbfe843-94d7-4c9c-989e-5338cf96774d.mp4

**Expected behavior**
Native build should also preserve it

**Logs**
If applicable, add logs to help explain your problem.

**Environment (please complete the following information):**
 - OS: [e.g. "Linux 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux"]
 - Output of the mvn -version` command
 - Kaoto Version [e.g. 1.0]

**Additional context**
