### ISSUE TITLE
Support KNative Eventing

### ISSUE THREAD

**Issue by Delawen** [KaotoIO/kaoto-backend#62]
We need to support `eventing.knative.dev` elements:

```
      ref:
        kind: Broker
        apiVersion: eventing.knative.dev/v1
        name: default
      properties:
        type: example
```

Right now, as it is not a kamelet, it does not get recognized as a valid step for the graphical side, although it can get deployed.
