### ISSUE TITLE
[BUG] 2nd Integration CRD is added if metadata exists on JSON>YAML

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto-backend#717]
**Describe the bug**
When UI sends integration JSON with topmost `metadata` defined, backend returns 2 Integration CRDs.

#### Request
```json
{
    "flows": [
        {
            "id": "route-2788",
            "dsl": "Integration",
            "description": "",
            "metadata": {},
            "params": [],
            "steps": []
        }
    ],
    "properties": {},
    "metadata": {
        "beans": [
            {}
        ]
    }
}
```

#### Response
```yaml
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: Integration1687876469547
spec:
  flows:
  - from:
      uri: null
      steps: []
---
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: ''
spec:
  flows:
  - from:
      uri: null
      steps: []
```

**To Reproduce**
1. Choose `Integration`
2. Click `Beans`
3. Click `Add new`
4. See browser network tab

**Expected behavior**
No 2nd Integration CRD, and beans are added into `/spec/flows/beans`

**Comment by igarashitm** [comment]
Verified this runs fine
```yaml
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: example
spec:
  flows:
    - from:
        uri: "timer:tick"
        steps:
          - set-body:
                simple: "${ref:myBean}"
          - to:
              uri: "log:info"
    - beans:
        - name: myBean
          type: org.apache.camel.model.FromDefinition
          properties:
            uri: foo
```
