### ISSUE TITLE
[BUG] Aws cloudtrail is removed from Kamelet defintion

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-backend#721]
**Describe the bug**

initila template route inside the kamelet:
```
  template:
    from:
      uri: "aws-cloudtrail:cloudtrail"
      parameters:
        secretKey: "{{?secretKey}}"
        accessKey: "{{?accessKey}}"
        region: "{{region}}"
        eventSource: "{{?eventSource}}"
        useDefaultCredentialsProvider: "{{useDefaultCredentialsProvider}}"
        uriEndpointOverride: "{{?uriEndpointOverride}}"
        overrideEndpoint: "{{overrideEndpoint}}"
        maxResults: "{{maxResults}}"
      steps:
      - to: "kamelet:sink"
  ```
which is modified to:
```
  template:
    from:
      uri: null
      steps:
      - to:
          uri: kamelet:sink
```

**To Reproduce**
1. Open https://github.com/apache/camel-kamelets/blob/3.20.x/kamelets/aws-cloudtrail-source.kamelet.yaml

**Expected behavior**

No data loss

**Logs**
If applicable, add logs to help explain your problem.

**Environment (please complete the following information):**

**Additional context**

i'm able to add aws-cloudtrail from UI
