### ISSUE TITLE
[BUG] Integration CRD: Missing multiple route support

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto-backend#733]
**Describe the bug**
The multiple route support for Integration CRD is missing. The `IntegrationStepParserService` concatenates all the steps into one route.

https://github.com/KaotoIO/kaoto-backend/assets/265462/39349886-63d0-4cf2-a35e-ea3c4b5c1288

#### Multi-route Integration

```yaml
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: integration93
spec:
  flows:
  - from:
      uri: 'timer:1'
      steps:
      - to:
          uri: 'log:1'
  - from:
      uri: 'timer:2'
      steps:
      - to:
          uri: 'log:2'
```

**To Reproduce**
1. Choose Integration
2. Paste the multi-route Integration source above
3. Click sync button

**Expected behavior**
Multiple routes are displayed on the canvas.
