### ISSUE TITLE
[BUG] Syncing a Kamelet or KameletBinding with a description returns an empty flow

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-backend#737]
**Describe the bug**

**To Reproduce**
1. Open the source code editor
2. Fill in the following YAML

<details>
  <summary>Yaml</summary>

```yaml
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: route-4127
spec:
  description: |-
      Receive all text messages that people send to your telegram bot.
  source:
    properties: {}
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: aws-cloudtrail-source
    types: {}
  sink:
    properties: {}
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: aws-cloudwatch-sink
    types: {}
```

</details>

4. Press `sync`
5. See the console error as the flow is empty

**Expected behavior**
The backend should return a flow without steps but the rest of the information, e.g.:

<details>
<summary>JSON</summary>

```json
{
	"flows": [
		{
			"steps": [],
			"metadata": {
				"labels": {
					"camel.apache.org/kamelet.type": "action"
				},
				"annotations": {},
				"additionalProperties": {},
				"name": "route-2782-action",
				"definition": {
					"properties": {},
					"title": ""
				},
				"beans": null,
				"dependencies": [
					"camel:core"
				],
				"spec": {
					"definition": {
						"properties": {},
						"title": ""
					},
					"dependencies": [
						"camel:core"
					],
					"template": {}
				}
			},
			"parameters": [],
			"dsl": "Kamelet"
		}
	]
}
```

</details>
