### ISSUE TITLE
[BUG] An empty route is generating a null step

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-backend#738]
**Describe the bug**
When adding an empty route through the YAML source file, it generates an array with a `null` step.

**To Reproduce**
the steps are:

1. Using the source code editor, fill this YAML and sync it

<details>
<summary>YAML</summary>

```yaml
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: Integration-1
spec:
  flows:
  - route:
      id: route-1234
      from:
        uri: cron:cron
        parameters:
          schedule: '1000'
        steps:
        - set-body:
            simple: body
        - to:
            uri: log:log1
  - route:
      id: route-4321
      from:
        uri: timer:test
        steps:
        - to:
            uri: log:log2
```

</details>

2. Append the following empty route at the end of the file:

<details>
<summary>YAML</summary>

```yaml
  - route:
      from:
        uri: null
        steps: []
```

</details>

3. sync again and notice the browser console.

**Expected behavior**
It should return a single Integration CRD with 3 flows in it, with the third one being completely empty.

**Logs**
```
TypeError: can't access property "name", step is null
```
