### ISSUE TITLE
[BUG] last `to` in kafka-ssl-sink-kamelet.yaml is removed

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-backend#758]
**Describe the bug**

last `to` in kafka-ssl-sink-kamelet.yaml is removed 

**To Reproduce**
1. Open Source code editor
2. Paste content from https://github.com/apache/camel-kamelets/blob/v3.20.6/kamelets/kafka-ssl-sink.kamelet.yaml
3. Click sync
--> the last to section is removed
```
        - to:
            uri: '{{kafka-ssl-sink-local}}:{{topic}}'
            parameters:
              configuration: '#bean:{{kafka-ssl-sink-configuration-local}}'
```

**Expected behavior**

**Logs**
If applicable, add logs to help explain your problem.

**Environment (please complete the following information):**
red.ht/kaoto-snapshot

**Additional context**
