### ISSUE TITLE
Resource of type integration creating empty flow on cluster

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto-backend#821]
**Describe the bug**
When user tries to deploy the resource of type "integration" on cluster - there is only empty flow created:

```
  flows:
    - from: null
```

In Kaoto, the flow resource looked like this:
```
  flows:
  - route:
      id: route-1562
      from:
        uri: timer:test
        steps:
        - to:
            uri: log:test
```

KameletBinding resource it works with no problem.

**To Reproduce**
1. Deploy Kaoto on a cluster
3. Deploy camel-k operator
4. Create sample integration flow
5. See error

**Expected behavior**

The resource should be created

**Environment (please complete the following information):**
 - Output of the mvn -version` command
 - Kaoto Version [e.g. 1.2]

**Recording**
![Peek 2023-08-02 10-47](https://github.com/KaotoIO/kaoto-backend/assets/4180208/d7e26cdb-a2bf-41d8-b3cf-493a0902bea1)
