### ISSUE TITLE
[BUG] Cannot parse file with when -> simple -> expression , force to use when -> simple and directly provide the String

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-backend#865]
**Describe the bug**

Cannot parse file with when -> simple -> expression , force to use when -> simple and directly provide the String

**To Reproduce**
1. Go to source editor and paste:
```
- route:
    id: route-3893
    from:
      uri: 'timer:'
      steps:
      - choice:
          when:
          - simple:
              expression: condition1
            steps:
            - log:
                message: reproducer
  ```

2. Click onSync
3. The choice is missing
In more complex case, the full route might not be displayed (but not found simple reproducer)

**Expected behavior**

**Logs**
```
2023-09-18 09:24:50,603 ERROR [io.kao.bac.cam.mod.dep.kam.ste.FlowStepDeserializer] (executor-thread-2) Error trying to deserialize step: Cannot deserialize value of type `java.lang.String` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: io.kaoto.backend.camel.model.deployment.kamelet.step.ChoiceFlowStep["choice"]->io.kaoto.backend.camel.model.deployment.kamelet.step.choice.SuperChoice["when"]->java.util.ArrayList[0]->io.kaoto.backend.camel.model.deployment.kamelet.step.choice.Choice["simple"])
```

**Environment (please complete the following information):**
 - OS: [e.g. "Linux 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux"]
 - Output of the mvn -version` command
 - Kaoto Version [e.g. 1.0]

**Additional context**
